// Generated by CoffeeScript 1.7.1
wx.ready(function() {
  wx.onMenuShareTimeline({
    title: '',
    link: '',
    imgUrl: '',
    success: function() {},
    cancel: function() {},
    fail: function() {},
    complete: function() {},
    trigger: function() {}
  });
  return wx.onMenuShareAppMessage({
    title: '',
    desc: '',
    link: '',
    imgUrl: '',
    type: '',
    dataUrl: '',
    success: function() {},
    cancel: function() {},
    fail: function() {},
    complete: function() {},
    trigger: function() {}
  });
});
