// Generated by CoffeeScript 1.7.1
var Vue, appView;

require('zepto');

Vue = require('vue');

appView = new Vue({
  el: document.body,
  data: {
    currentView: 'main'
  },
  components: {
    'main': require('./components/main/layout.vue')
  }
});
