// Generated by CoffeeScript 1.7.1
var Vue, appView;

Vue = require('vue');

appView = new Vue({
  el: document.body,
  data: {
    currentView: 'loading'
  },
  components: {
    'loading': require('./components/loading'),
    'c-share': require('./components/share')
  }
});
